version: '2'
services:
  mysql:
    container_name: mysql
    restart: always
    image: mysql:5.7
    ports:
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'admin'
      MYSQL_USER: 'admin'
      MYSQL_DATABASE: 'EscolaGanesh'
      MYSQL_PASS: 'admin'

